# Generated by Django 6.0.3 on 2026-04-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='bi-trophy', help_text='Clase de Bootstrap Icons, ej: bi-trophy', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(upload_to='landing/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de galería',
                'verbose_name_plural': 'Fotos de galería',
                'ordering': ['orden', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='landing/instructor/')),
                ('experiencia', models.CharField(blank=True, help_text='ej: 15 años de experiencia', max_length=100)),
            ],
            options={
                'verbose_name': 'Información del instructor',
                'verbose_name_plural': 'Información del instructor',
            },
        ),
    ]
