# Generated by Django 6.0.3 on 2026-04-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='icono',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la card de esta disciplina', null=True, upload_to='landing/disciplinas/'),
        ),
    ]
