# Generated by Django 6.0.3 on 2026-04-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Berserker Ronin', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('mensaje_bienvenida', models.TextField(blank=True, default='¡Bienvenido a Berserker Ronin! Estamos felices de tenerte con nosotros.')),
            ],
            options={
                'verbose_name': 'Configuración del Dojo',
                'verbose_name_plural': 'Configuración del Dojo',
            },
        ),
    ]
