# Generated by Django 6.0.3 on 2026-03-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
