# Generated by Django 6.0.3 on 2026-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('disciplina', models.CharField(choices=[('karate', 'Karate'), ('mma', 'MMA'), ('ambas', 'Ambas')], max_length=10)),
                ('cinturon', models.CharField(choices=[('blanco', 'Blanco'), ('amarillo', 'Amarillo'), ('naranja', 'Naranja'), ('verde', 'Verde'), ('azul', 'Azul'), ('marron', 'Marrón'), ('negro', 'Negro'), ('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['nombre'],
            },
        ),
    ]
