# Generated by Django 6.0.3 on 2026-04-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='monto_mensualidad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto fijo mensual de este alumno. Dejar vacío si no aplica.', max_digits=8, null=True),
        ),
    ]
